Improve docs wording, formatting, fixes #603
sobolevn/git-secret pull request #604
Opened 2020-09-11 14:34 UTC by teutat3s

What does this implement/fix? Explain your changes.
---------------------------------------------------
Implements minor wording, formatting changes to the GitHub pages documentation at https://git-secret.io

Does this close any currently open issues?
------------------------------------------
This would close #603 

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
Thank you for creating and maintaining `git-secret`! I hope my minor changes can one day be included and be a little contribution to this nice project. I'm always open for feedback and improving this PR.

2020-09-11 15:08 UTC, sobolevn reviewed
Thanks a lot! Passing this to @joshrabinowitz to be reviewed. I am not a native speaker.

2020-09-11 15:08 UTC, joshrabinowitz commented
This is great, thank you @teutat3s ! Will read carefully and merge soon.

2020-09-11 15:13 UTC, teutat3s commented
Thanks for the quick reactions guys! 

@sobolevn I left you a message on Keybase with a small question about `git-secret` - I hope that's the correct channel to ask such questions, if not I could create an issue in this repo, too.

2020-09-11 15:25 UTC, joshrabinowitz requested changes
I wrote a few comments below which I think improve these docs even a little more. 
Thank you again for this PR! I look forward to merging it.

2020-09-11 15:25 UTC, joshrabinowitz commented on _posts/2020-03-05-git-secret.md
> +`.gitignore`, otherwise `git-secret` won't allow you to add them, as these files could be stored unencrypted. Actually, in the default configuration it will automatically add the files to `.gitignore
Please replace the last sentence with:

"In the default configuration, `git-secret add` will automatically add the unencrypted versions of the files to `.gitignore` for you."

2020-09-11 15:25 UTC, joshrabinowitz commented on _posts/2020-03-05-git-secret.md
> +To make sure you get the original public keys of the indicated persons, be sure to use a secure channel to transfer it, or use a service you trust like Keybase to retrieve their public key. Otherwise
please change to  

"or use a service you trust, preferably one that uses encryption such as Keybase, to retrieve their public key".

2020-09-11 15:25 UTC, joshrabinowitz commented on _posts/2020-03-05-git-secret.md
>  This can be done in your shell environment file or with each `git-secret` command.
Please say something like:

See the man page for `git-secret` for an explanation of the environment variables `git-secret` uses.

2020-09-12 13:44 UTC, joshrabinowitz commented on _posts/2020-03-05-git-secret.md
>  This can be done in your shell environment file or with each `git-secret` command.
I should have read more carefully before making my last suggestion; I see that git-secret's env vars are described just below here. Can you please change the sentence to say:

"See below, or the man page for git-secret, for an explanation of the environment variables git-secret uses."

Then I'll go ahead and merge this PR.

2020-09-12 13:51 UTC, joshrabinowitz commented
@teutat3s, I just realized this PR conflicts with how the _posts directory in the `gh-pages` branch works.

The files in the `gh-pages` branches' `_posts` directory are automatically generated from  git-secret's man pages. 
(See https://github.com/sobolevn/git-secret/blob/gh-pages/create_posts.sh, and the Makefile in that directory)

So these changes should be applied to the .ronn files in man/man1 and man/man7 in a branch originated from the master branch.

2020-09-12 16:26 UTC, teutat3s commented
Abandoned in favor of #606

2020-09-12 16:26 UTC, closed without merging